my_project/my1app/urls.py
from django.urls import include
from django.urls import path
from my1app import views

#Template tagging

app_name = 'my1app'

urlpatterns = [   
    path('registration/', views.registration, name='registration'),
    path('user_login/', views.user_login, name='user_login'),
]

my_project/my_project/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from my1app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('home/',include('my1app.urls')),
    path('relative/',views.relative,name='relative'),
    path('logout/',views.user_logout,name='logout'),
    path('other/',views.other,name='other'),
     path('special/',views.special,name='special'), 
]

my_project/my1app/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    #additional attributes 
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to = 'profile_pics',blank =True)

    def __str__(self) -> str:
        return self.user.username

my_project/my1app/forms.py
from django import forms
from django.contrib.auth.models import User
from my1app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():       
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic') 

my_project/my1app/views.py
from django.shortcuts import render
from my1app.forms import UserForm,UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login,logout,authenticate

# Create your views here.

def index(request):
    context_dict = {'text':'helo hola','number':2000}
    return render(request,'my1app/index.html',context_dict)
    
def relative(request):
    return render(request,'my1app/relative_url_templates.html')
    
def other(request):
    return render(request,'my1app/other.html')

def registration(request):

    registered = False
    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid and profile_form.is_valid:
            #save user attributes
            user =user_form.save()
            user.set_password(user.password)
            user.save()

            #save profile fields
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
                        
    return render(request,'my1app/registration.html',
    {'user_form':user_form,'profile_form':profile_form,'registered':registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("yu log indd")

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")   

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('special'))
            else:
                return HttpResponse("not actibe") 
        else:
            print("failed")
            return HttpResponse("invalid fields")
    else:
        return render(request, 'my1app/login.html')                    

my_project/templates/my1app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <!-- CSS only -->
    <link rel="stylesheet"  type ="text/css" href="{% static '..//static/semantic-ui/semantic.css' %}">
</head>
<body>
    <div class="ui container">
        <div class="ui secondary menu"> 
        
            <a class="item" href="{% url 'index' %}">Brand</a>
            <a class="item" href="{% url 'admin:index' %}">admin</a>
            <a class="item" href="{% url 'other' %}">other</a>
            <a class="item" href="{% url 'my1app:registration' %}">Sign up</a>

            {% if user.is_autenticated %}
            <a class="item" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="item" href="{% url 'my1app:user_login' %}">Login</a>
            {% endif %}


         </div>
         
         <div class="ui container">
            {% block body_block %}
            <!-- nothing here -->
            {% endblock %}
         </div>

    </div>
    
</body>
</html>

my_project/templates/my1app/index.html
<!DOCTYPE html>
{% extends "my1app/base.html" %}
{% block body_block%}

    <div class="ui segments">
        <div class="ui segment">
            <h1>Welcome to index.html </h1>
            <p>thisis super</p>
            <h3>{{text|upper}}</h3>
            {{number}}
        </div>
        <div class="ui segment">
            <p>there should be a lot.</p>
        </div>
    </div>
{% endblock %}

my_project/templates/my1app/login.html
<!DOCTYPE html>
{% extends 'my1app/base.html' %}
{% block body_block %}

<div class="ui segments">
    <div class="ui header segment">
        <h3>Login here!</h3>
    </div>
    <div class="ui segment">
        <form class="ui form" action="{% url 'my1app:user_login' %}" method="post">
            {% csrf_token %}
            <div class="field">
                <label>Username</label>
                <input type="text" placeholder="Username" name="username">
              </div>
              <div class="field">
                <label>Password</label>
                <input type="password" name="password">
              </div>
              <input type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

my_project/templates/my1app/other.html
<!DOCTYPE html>

{% extends "my1app/base.html" %}
{% block body_block%}
<h1>Welcome to others </h1>
<p>it worked super</p>
{% endblock %}

my_project/templates/my1app/registration.html
<!DOCTYPE html>
{% extends 'my1app/base.html'%}
{% load static %}

{% block body_block %}

<div class="ui container">
    {% if registered %}
    <h1>Thank you registred</h1>
    {% else %}
    <h2>Register here </h2>
    <form class="ui form" method="post" enctype="multipart/form-data">
        <div class="ui two column very relaxed grid">
            <div class="column">
                {% csrf_token %}
                {{user_form.as_p }} 
                {{profile_form.as_p}}  
                <input type="submit" value="Submit">
            </div>
        </div>
    </form>
    {% endif %}

</div>

{% endblock %}

my_project/templates/my1app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relatives </h1>
    <a href="{% url 'my1app:other' %}">go to the other page</a>
    <a href="{% url 'admin:index' %}">go to admin page</a>
    <a href="{% url 'index' %}">way to home</a>
</body>
</html>